apiVersion: v1
kind: Service
metadata:
  name: myjavaapp-svc
  labels:
      app: myjavaapp
spec:
  selector:
    app.kubernetes.io/name: myjavaapp
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 3001